### ISSUE TITLE
complete function never gets called in special case

### ISSUE THREAD

**Issue by tssajo** [pvorb/node-dive#12]
If the directory parameter passed to dive is not a directory (in my case it comes from user input, so it could be whatever garbage) then the complete function of dive never gets called... :(
Note: I noticed that you call in this case the first callback with an error object, but still, I would expect the complete function to be called when dive is finished.

**Comment by pvorb** [comment]
That's correct. If you could create a pull request, I'd merge it. At the moment I'm to busy to fix it on my own.

**Comment by tssajo** [comment]
PR is created. Let me know if you'd like to discuss it before merging.

**Comment by pvorb** [comment]
Closed. See #13.
